server_name @@HOST@@;

location ~ \.php(?:/|$) { return 404; }
location ~ /\. { return 404; }

client_max_body_size 0;

add_header X-Robots-Tag "none" always;

set $domjudgeRoot /opt/domjudge/domserver/webapp/public;
set $prefix "";

location = /domjudge { return 308 /$is_args$args; }
location ~ ^/domjudge/(.*)$ { return 308 /$1$is_args$args; }

location / {
    root $domjudgeRoot;
    try_files $uri @domjudgeFront;

    location /api/ {
        try_files $uri @domjudgeFrontApi;
    }
}

location @domjudgeFront {
	fastcgi_split_path_info ^(.+\.php)(/.*)$;
	fastcgi_pass domjudge;
	include fastcgi_params;
	fastcgi_param SERVER_NAME $host;
	fastcgi_param SCRIPT_FILENAME $domjudgeRoot/index.php;
	fastcgi_param SCRIPT_NAME $prefix/index.php;
	fastcgi_param REQUEST_URI $prefix$uri?$args;
	fastcgi_param DOCUMENT_ROOT $domjudgeRoot;
	fastcgi_param HTTPS $fastcgi_param_https_variable;
	internal;
}

location @domjudgeFrontApi {
	fastcgi_split_path_info ^(.+\.php)(/.*)$;
	fastcgi_pass domjudge;
	include fastcgi_params;
	fastcgi_param SERVER_NAME $host;
	fastcgi_param SCRIPT_FILENAME $domjudgeRoot/index.php;
	fastcgi_param SCRIPT_NAME $prefix/index.php;
	fastcgi_param REQUEST_URI $prefix$uri?$args;
	fastcgi_param DOCUMENT_ROOT $domjudgeRoot;
	fastcgi_param HTTPS $fastcgi_param_https_variable;
	internal;

	error_log /var/log/nginx/domjudge-api.log;
	access_log /var/log/nginx/domjudge-api.log;
}

add_header X-Frame-Options "DENY";

add_header Referrer-Policy "same-origin";
add_header X-Content-Type-Options "nosniff";
add_header X-XSS-Protection "1; mode=block";

error_log /var/log/nginx/domjudge.log;
access_log /var/log/nginx/domjudge.log;
