upstream domjudge {
	server unix:/var/run/php-fpm-domjudge.sock; # if using with etc/domjudge-fpm.conf
}

map $http_x_forwarded_proto $fastcgi_param_https_variable {
	default $https;
	https 'on';
}

server {
	listen 80;
	listen [::]:80;

	send_timeout 36000s;
	include /opt/domjudge/domserver/etc/nginx-conf-inner;
}
